name: PR Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  pr-pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Build, Unit Test and Scala Spark Integration tests
        run: sbt -v +test
