name: PR Checks

on: pull_request

jobs:
  pr-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Build and Test
        run: sbt -v +test
      - name: Create fat jar
        run: sbt assembly
      - name: docker build
        run: docker build -t spark-with-weaviate .
      - name: Run sample Scala DS
        run: docker run spark-with-weaviate /opt/spark/bin/spark-shell -i /opt/spark/example.scala
